### ISSUE TITLE
Tables including mixed job sizes are confusing

### ISSUE THREAD

**Issue by rjrw** [Dundee/benchmarksgame#1]
e.g. on
  https://pybenchmarks.org/u64q/performance.php?test=nbody
the results in the table include timings for each of N=50,000, N=500,000 and N=5,000,000

I find this makes it difficult to compare the speed for different packages, as values for different N are interleaved.  The originator of the CLBG package confirms that this behaviour is not as intended.

I think it would be better to only report values for just one value of N in each table: the main CLBG pages default to the results for the largest N.

Thanks.

**Comment by dundee** [comment]
Should be better now: https://pybenchmarks.org/u64q/performance.php?test=spectralnorm

Results of only one timing are shown.

Thanks!

**Comment by rjrw** [comment]
OK, looks better to me.  Many thanks!
